language: node_js
node_js:
- 6
- 7
addons:
  # Required to compile native modules on newer Node.js versions
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.9
    packages:
    # install toolchains
    - libmagic-dev
    - libatlas-base-dev
    - alsa-tools
    - alsa-utils
    - libzmq3-dbg
    - libzmq3-dev
    - libzmq3
    - gcc-4.8
    - g++-4.8
    - clang-3.8
services:
  - mongodb
env:
- CXX=g++-4.8
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/117063f9c1031b17e557
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: jimmy.aumard@gmail.com
  api_key:
    secure: LOVtqNiZ830BcrF+d1CFbAwd6PJgfCHd+raS4u9Oe9mRHh8Y3KcMCwFJGGwnis8hTI6YdS7PFdw304TE00ErzywFWOdkyOOjCEUq6mVEod6ojeUOTSw9AKOYwv+JBw795QtBAKdxCi+07oPqqZN2wGicw0aFTlbt/+boT4k+Zqbm20j+l+EY6zdnqFG0aII8dToTMS0Nu1Dk71nv4UZrcNg2ajbOx0BYxls02NuOO17zQTw7RbCE33MBfdh4vZMFzR6sV/3XWEzg2BEF7z39OR0Crk1FP+tFSfHP7zlUom39GZoBQnrzBLKNndc8RF7OrB98ieFcDfviOx42A2th+GUKVJyg8QcS2zfoYROt4ZbXOprCdUE917OZW7ytG3jPE5KiONz7ge3pafGjZH+VP+bgi9EBhPYCyzpfB2Cvv7pR/CaXQXscUA3CJgbutI7MyhPUf7U+JNruOESnthX52EJ3TXCp0tncaJcJhPGJac7ZPMRSNQ7zXfsntDJO+k6yiXHwmUN7kmEXL456mNGvrglb8ZQuFlfyfTmxKRffl1BMpbNmpYVj1ddwB+TYpZQ1R4cCKHcBwkCQ0oEF8/p6R2CeB+x/9cxKOUqrwz5X6Zfe4l/pv3q4ijNsb9Tf5sTdhgEn7kixet9wqNT/tXeVX3p+bebmls6y57IpiToAV8A=
  on:
    tags: true
    repo: mylisabox/lisa-plugin-example
    node: 6
