language: node_js
node_js:
- 6
- 7
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.9
    packages:
    - libmagic-dev
    - libatlas-base-dev
    - libzmq3-dbg
    - libzmq3-dev
    - libzmq3
    - gcc-4.8
    - g++-4.8
    - clang-3.8
services:
- mongodb
env:
- CXX=g++-4.8
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/117063f9c1031b17e557
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: jimmy.aumard@gmail.com
  api_key:
    secure: b9erc9f2wQgKX+v/O8eL5MDNiBN4aMyhuxcicXjyoGNeMdddVtlgfGgdOgGK4qa85ED2wkeYHvnq3gweOxdndUyKhd/q8qPJMOPLwU9aMvXgQZk2x3unKdS9mwgNzTjuETahQ/OIGBvfht8FPsQGdV5H+qAbRU/Q1ZUUkBlaVyb3m7VZ1UBFOmutaPHt/94GjhB6QvTbngOB7QyIuvnlkGexsXf7v0pl+1BErlX6/j8OnHd+DFSg76jGB57dV2ZrywwP2SgTB4o6nCXXjj4nHvR4VU6q4u8EV1b4lWKPOyxkG4qNyF3KZuifnNtbAQL6g/UzjPiB7dOdfSb5NAggP/O04VeU/KICIk8uVysXZaKKH3fZMK3HvB65MoSJZK0qs3zwO+mMaF2HteK5IJgCAm+iX8WQPuBtsxLURuutre/WwkBHVNE4wDFABLii5gvzh+R95Ot4OcJfLZJyk1inxu50D/cBWPlhb4LYMz9DasXWYsHvfO00d2EQChLHtHfyCqSkkDdEHuoSthY/v4ICVCim2K3gd1PhHj1mG4u2Y4CL3dJLkio3zaQ3T+pAdFqjGJ8WsEI0NBxIvcTvYy4tSb/8RztA+7nQ3CA0wqitDIuv0fqtgUDWj1XbeyaE7vHBfqqUuaw7GADmZ6dosex6CJt1KtbeJWaI3NBZcEJADeY=
  on:
    tags: true
    repo: mylisabox/lisa-plugin-example
    node: 6
